// Code generated by ADL CLI v0.34.1. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	server "github.com/inference-gateway/adk/server"
	envconfig "github.com/sethvargo/go-envconfig"
	zap "go.uber.org/zap"
	yaml "gopkg.in/yaml.v3"

	config "github.com/inference-gateway/mock-agent/config"
	tools "github.com/inference-gateway/mock-agent/tools"

	logger "github.com/inference-gateway/mock-agent/internal/logger"
	mock "github.com/inference-gateway/mock-agent/internal/mock"
)

var (
	Version          = "0.1.6"
	AgentName        = "mock-agent"
	AgentDescription = "A2A agent server for mocking and testing. Uses a mock LLM client - no API keys required!"
)

// skillsDir is the directory the runtime scans for skill manifests at
// startup. Override with A2A_SKILLS_DIR.
const skillsDir = "skills"

// loadSkillsManifest walks the configured skills directory, reads each
// <skill>/SKILL.md, extracts the YAML frontmatter (name + description),
// and returns an `AVAILABLE SKILLS:` block to append to the system
// prompt. SKILL.md bodies are NOT inlined — the model must call the
// Read tool to load a skill's playbook on demand. Returns "" when the
// directory is missing or has no valid manifests.
func loadSkillsManifest(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	dirs := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dirs = append(dirs, e.Name())
	}
	sort.Strings(dirs)

	type skillFrontmatter struct {
		Name        string `yaml:"name"`
		Description string `yaml:"description"`
	}

	var manifest strings.Builder
	for _, id := range dirs {
		path := filepath.Join(dir, id, "SKILL.md")
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		fmBytes, ok := extractFrontmatter(data)
		if !ok {
			continue
		}
		var fm skillFrontmatter
		if err := yaml.Unmarshal(fmBytes, &fm); err != nil {
			continue
		}
		if fm.Name == "" || fm.Description == "" {
			continue
		}
		if manifest.Len() == 0 {
			manifest.WriteString("AVAILABLE SKILLS:\n")
			manifest.WriteString("Skills are reusable instructions for specific tasks. When a task matches a\n")
			manifest.WriteString("skill's description, read the SKILL.md file at the listed path using the Read\n")
			manifest.WriteString("tool, then follow its instructions.\n\n")
		}
		fmt.Fprintf(&manifest, "- %s: %s\n  Path: %s\n", fm.Name, fm.Description, path)
	}
	return manifest.String(), nil
}

// extractFrontmatter returns the bytes between the opening and closing
// `---` fences of a SKILL.md file (without including the fences
// themselves). The second return value is false when no frontmatter is
// found.
func extractFrontmatter(content []byte) ([]byte, bool) {
	bom := []byte{0xEF, 0xBB, 0xBF}
	buf := bytes.TrimPrefix(content, bom)
	buf = bytes.TrimLeft(buf, "\r\n\t ")
	if !bytes.HasPrefix(buf, []byte("---")) {
		return nil, false
	}
	rest := buf[3:]
	rest = bytes.TrimLeft(rest, "\r\n")
	idx := bytes.Index(rest, []byte("\n---"))
	if idx < 0 {
		return nil, false
	}
	return rest[:idx], true
}

func main() {
	ctx := context.Background()

	var cfg config.Config
	if err := envconfig.Process(ctx, &cfg); err != nil {
		log.Fatal("failed to load config:", err)
	}

	// Initialize logger
	l, err := logger.NewLogger(ctx, &cfg)
	if err != nil {
		log.Fatal("failed to initialize logger:", err)
	}

	l.Info("starting " + AgentName + " agent (version: " + Version + ", environment: " + cfg.Environment + ")")

	resolvedSkillsDir := skillsDir
	if v := os.Getenv("A2A_SKILLS_DIR"); v != "" {
		resolvedSkillsDir = v
	}
	skillsPrompt, err := loadSkillsManifest(resolvedSkillsDir)
	if err != nil {
		l.Warn("failed to load skills manifest, continuing without them", zap.Error(err))
	} else if skillsPrompt != "" {
		l.Info("loaded skills manifest into system prompt", zap.String("dir", resolvedSkillsDir))
	}

	// Create toolbox with default tools (like input_required, create_artifact etc)
	toolBox := server.NewDefaultToolBox(&cfg.A2A.AgentConfig.ToolBoxConfig)

	// Register Read built-in
	readTool, err := tools.NewReadTool(ctx, l)
	if err != nil {
		l.Fatal("failed to construct Read tool", zap.Error(err))
	}
	toolBox.AddTool(readTool)
	l.Info("registered built-in: Read")

	// Register echo tool
	echoTool := tools.NewEchoTool()
	toolBox.AddTool(echoTool)
	l.Info("registered tool: echo (Echo back the input message (useful for basic connectivity tests))")

	// Register delay tool
	delayTool := tools.NewDelayTool()
	toolBox.AddTool(delayTool)
	l.Info("registered tool: delay (Simulate slow responses with configurable delays)")

	// Register error tool
	errorTool := tools.NewErrorTool()
	toolBox.AddTool(errorTool)
	l.Info("registered tool: error (Simulate error conditions for testing error handling)")

	// Register random_data tool
	randomDataTool := tools.NewRandomDataTool()
	toolBox.AddTool(randomDataTool)
	l.Info("registered tool: random_data (Generate random test data)")

	// Register validate tool
	validateTool := tools.NewValidateTool()
	toolBox.AddTool(validateTool)
	l.Info("registered tool: validate (Validate input against common patterns)")

	llmClient := mock.NewMockLLMClient()
	l.Info("using mock LLM client (no external API calls)")

	systemPrompt := `You are a mock AI assistant designed for testing and development purposes.

You have access to several mock tools that demonstrate different testing scenarios:
- echo: Simply echo back the input message (useful for basic connectivity tests)
- delay: Simulate slow responses with configurable delays
- error: Simulate error conditions for testing error handling
- random_data: Generate random test data
- validate: Validate input against common patterns

When responding:
- Be clear and predictable in your responses
- Include relevant metadata about the request
- Support both streaming and non-streaming modes
- Handle edge cases gracefully

Your purpose is to provide consistent, reproducible responses for testing A2A protocol implementations.
`
	if skillsPrompt != "" {
		systemPrompt = systemPrompt + "\n\n" + skillsPrompt
	}

	agent, err := server.NewAgentBuilder(l).
		WithConfig(&cfg.A2A.AgentConfig).
		WithLLMClient(llmClient).
		WithToolBox(toolBox).
		WithMaxChatCompletion(cfg.A2A.AgentConfig.MaxChatCompletionIterations).
		WithSystemPrompt(systemPrompt).
		Build()
	if err != nil {
		l.Fatal("failed to create agent", zap.Error(err))
	}

	artifactService, err := server.NewArtifactService(&cfg.A2A.ArtifactsConfig, l)
	if err != nil {
		l.Warn("artifact service could not be created - check A2A_ARTIFACTS_ENABLE environment variable", zap.Error(err))
		l.Info("continuing without artifact service support")
		artifactService = nil
	}

	artifactsServer, err := server.
		NewArtifactsServerBuilder(&cfg.A2A.ArtifactsConfig, l).
		WithArtifactService(artifactService).
		Build()
	if err != nil {
		l.Warn("artifacts server could not be created", zap.Error(err))
		l.Info("continuing without artifacts server")
		artifactsServer = nil
	}

	a2aServer, err := server.NewA2AServerBuilder(cfg.A2A, l).
		WithAgent(agent).
		WithAgentCardFromFile(".well-known/agent-card.json", map[string]any{
			"name":        AgentName,
			"version":     Version,
			"description": AgentDescription,
			"url":         cfg.A2A.AgentURL,
		}).
		WithArtifactService(artifactService).
		WithDefaultBackgroundTaskHandler().
		WithDefaultStreamingTaskHandler().
		Build()
	if err != nil {
		l.Fatal("failed to create A2A server", zap.Error(err))
	}

	go func() {
		l.Info("starting A2A server", zap.String("port", cfg.A2A.ServerConfig.Port))
		if err := a2aServer.Start(ctx); err != nil {
			l.Fatal("server failed to start", zap.Error(err))
		}
	}()

	if artifactsServer != nil {
		go func() {
			l.Info("starting A2A artifacts server", zap.String("port", cfg.A2A.ArtifactsConfig.ServerConfig.Port))
			if err := artifactsServer.Start(ctx); err != nil {
				l.Fatal("artifacts server failed to start", zap.Error(err))
			}
		}()
	}

	l.Info("mock-agent agent running successfully",
		zap.String("port", cfg.A2A.ServerConfig.Port),
		zap.String("environment", cfg.Environment))

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	l.Info("shutdown signal received, gracefully stopping server...")
	a2aServer.Stop(ctx)
	if artifactsServer != nil {
		artifactsServer.Stop(ctx)
	}
	l.Info("mock-agent agent stopped")
}
