// Code generated by ADL CLI v0.48.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package config

import (
	serverConfig "github.com/inference-gateway/adk/server/config"
)

// Config represents the application configuration
type Config struct {
	// A2A configuration (all A2A_ prefixed vars)
	A2A serverConfig.Config `env:",prefix=A2A_"`

	// Custom configuration sections
	Telemetry TelemetryConfig `env:",prefix=TELEMETRY_"`
}

// TelemetryConfig represents the telemetry configuration
type TelemetryConfig struct {
	Enable  bool   `env:"ENABLE,default=false"`
	Log     string `env:"LOG,default=map[enable:false endpoint:http://localhost:4318]"`
	Metrics string `env:"METRICS,default=map[host: idle_timeout:60s port:9090 read_timeout:30s write_timeout:30s]"`
	Trace   string `env:"TRACE,default=map[enable:false endpoint:http://localhost:4318]"`
}
